substitutions:
  inverter_maximum_power: "6500"
  version: "1"
  name: dtu-wbs1-v001
  friendly_name: DTU WBS1-V001

esp32:
  board: esp32-c3-devkitm-1

packages:
  core: !include packages/core-local.yaml
  inverter: !include packages/inverter.yaml
  grid: !include packages/grid.yaml
  temperature: !include packages/temperature.yaml
  battery: !include packages/battery.yaml
  battery-48v: !include packages/battery-48v.yaml
  # pv: !include packages/pv.yaml
  # parallel: !include packages/parallel.yaml
  # bms-48v: !include packages/bms-48v.yaml
  dtu-wbs1-v001: !include packages/dtu-wbs1-v001.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
