substitutions:
  inverter_maximum_power: "6500"
  version: "2"
  name: dtu-wbs1-v001
  friendly_name: DTU WBS1-V001

esp32:
  board: esp32-c3-devkitm-1

packages:
  inv_8851:
    url: https://github.com/lufton/esphome-inv-8851
    ref: main
    files:
      - packages/core.yaml
      - packages/inverter.yaml
      - packages/grid.yaml
      - packages/temperature.yaml
      - packages/battery.yaml
      - packages/battery-48v.yaml
      # - packages/pv.yaml
      # - packages/parallel.yaml
      # - packages/bms-48v.yaml
      - packages/dtu-wbs1-v001.yaml
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
