substitutions:
  name: wifi-plug-pro-05
  friendly_name: Wi-Fi Plug Pro-05
  inverter_maximum_power: "4500"
  version: "2" # this should be 1 for older revisions and 2 for newer, try different if you see message in the logs
  voltage: "48" # this could be 24 or 48

esp8266:
  board: d1_mini

packages:
  core: !include packages/core-local.yaml
  inverter: !include packages/inverter.yaml
  grid: !include packages/grid.yaml
  temperature: !include packages/temperature.yaml
  battery: !include packages/battery-48v.yaml
  # pv: !include packages/pv.yaml
  # parallel: !include packages/parallel.yaml
  bms: !include packages/bms-48v.yaml
  wifi-plug-pro-05: !include packages/wifi-plug-pro-05.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

interval:
  interval: 1s
  then:
    if:
      condition: api.connected # mqtt.connected
      then:
        if:
          condition:
            light.is_off: srv_led
          then:
            light.turn_on: srv_led
      else:
        - light.turn_on: srv_led
        - delay: 500ms
        - light.turn_off: srv_led
