substitutions:
  name: wifi-plug-pro-05
  friendly_name: Wi-Fi Plug Pro-05
  inverter_maximum_power: "4500"
  version: "2" # this should be 1 for older revisions and 2 for newer, try different if you see message in the logs
  voltage: "24" # this could be 24 or 48

esp8266:
  board: d1_mini

packages:
  inv_8851:
    url: https://github.com/lufton/esphome-inv-8851
    ref: main
    files:
      - packages/core.yaml
      - packages/inverter.yaml
      - packages/grid.yaml
      - packages/temperature.yaml
      - packages/battery.yaml
      - packages/battery-24v.yaml
      # - packages/pv.yaml
      # - packages/parallel.yaml
      # - packages/bms-24v.yaml
      - packages/wifi-plug-pro-05.yaml
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

interval:
  interval: 1s
  then:
    if:
      condition: api.connected # mqtt.connected
      then:
        if:
          condition:
            light.is_off: srv_led
          then:
            light.turn_on: srv_led
      else:
        - light.turn_on: srv_led
        - delay: 500ms
        - light.turn_off: srv_led
