substitutions:
  battery_back_to_util_voltage_min: "40"
  battery_back_to_util_voltage_max: "58.4"
  battery_bulk_voltage_min: "48"
  battery_bulk_voltage_max: "58.4"
  battery_float_voltage_min: "48"
  battery_float_voltage_max: "58.4"
  battery_cut_off_voltage_min: "40"
  battery_cut_off_voltage_max: "48"
  battery_equalization_voltage_min: "50"
  battery_equalization_voltage_max: "59"
  total_charge_current_max: "130"
  util_charge_current_max: "110"

<<: !include battery.yaml