substitutions:
  battery_back_to_util_voltage_min: "20"
  battery_back_to_util_voltage_max: "29.2"
  battery_bulk_voltage_min: "24"
  battery_bulk_voltage_max: "29.2"
  battery_float_voltage_min: "24"
  battery_float_voltage_max: "29.2"
  battery_cut_off_voltage_min: "20"
  battery_cut_off_voltage_max: "24"
  battery_equalization_voltage_min: "25"
  battery_equalization_voltage_max: "29.5"
  total_charge_current_max: "150"
  util_charge_current_max: "140"

<<: !include battery.yaml